#!/bin/bash

# Header linea
echo processes n error time >> mach4.txt
p=1
for m in `seq 1 1 4`
do
    n=2
    for k in `seq 1 1 24` 
    do
        if [ $n -ge $p ]
        then
            result=$(mpirun -np $p ./mach4 vtest $n)
            echo $p $n $result >> mach4.txt
        fi
        n=$(($n*2))
    done
    p=$(($p*2))
done
